services: mongodb
language: node_js
node_js:
  - 8
install:
  - npm install
  - npm install --no-save booljs mongoose

deploy:
  provider: npm
  email: hola@pablodorado.com
  api_key: $NPM_API_KEY
  on:
    branch: master
    tags: true
